### ISSUE TITLE
Agregar información de variables a Wiki

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/embaco#1]
Agregar la siguiente infomación en la Wiki del proyecto

Latitud,
Longitud,
Región,
Departamento,
Fecha,
Hora,
Temperatura,
Velocidad del Viento,
Dirección del Viento,
Presión,
Punto de Rocío,
Cobertura total nubosa,
Precipitación (mm/h),
Probabilidad de Tormenta,
Humedad,
Pronóstico 

Fuente: http://www.pronosticosyalertas.gov.co/datos-de-pronostico

[Cra. 5 #5-2 a 5-104, Puerto López, Meta, Colombia.txt](https://github.com/jmencisom/embaco/files/1758726/Cra.5.5-2.a.5-104.Puerto.Lopez.Meta.Colombia.txt)

**Comment by jrcarvajal** [comment]
Seria bueno analizar que variables son las que se necesitan, debido a que las tarjetas como el arduino o Raspberry no tiene tantos puerto o socket de lectura de sensores.

**Comment by jmencisom** [comment]
Creo que el número de variables se reduce a (7):

1. Temperatura,
2. Velocidad del Viento,
3. Dirección del Viento,
4. Presión,
5. Cobertura total nubosa,
6. Precipitación (mm/h),
7. Humedad,

Los demás parámetros se calculan a partir de las anteriores.

**Comment by jmencisom** [comment]
¿Será que si encontramos 7 u 8 puertos?

**Comment by jrcarvajal** [comment]
Que bien, ya estoy desarrollando la aplicacion que lee los datos de la Rasberry, estos datos son almacenados de una base de datos, donde en cada tabla o relacion se almacena la informacion correspondiente a cada variable (ej. temperatura, presion,...). Esta aplicacion junto con la base de datos estará alojada en el servidor de la facultad.

**Comment by jmencisom** [comment]
Excelente Jesús. A la espera de ver los primeros resultados!

**Comment by jrcarvajal** [comment]
El Arduino tiene como 6 puertos input/output, la Rasberry tiene menos creo...  La solución seria manejar las dos tarjetas para dar cobertura a las variables.

**Comment by jrcarvajal** [comment]
Los primeros resultados se veran cuando tengamos al menos un sensor de los mencionados...

**Comment by jrcarvajal** [comment]
Seria comprar un sensor como el LM35 de temperatura para hacer pruebas...

**Comment by jmencisom** [comment]
https://github.com/jmencisom/embaco/wiki/Paper#design
