### ISSUE TITLE
Diseñar logo del proyecto

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/embaco#10]
Por favor diseñar un logo para el proyecto EMBaCo.

Adjuntar 3 propuestas para que el equipo seleccione la ganadora.

Gracias.

**Comment by jmencisom** [comment]
Por favor adjuntar las propuestas candidatas y escoger una de ellas.

**Fecha de entrega 12 de marzo**

**Comment by AO94** [comment]
![emback](https://user-images.githubusercontent.com/37197758/37496646-b9edfa4c-2881-11e8-8ffc-b40f54eb25f4.jpg)

**Comment by AO94** [comment]
A continuación adjunto varios diseños del logo para el proyecto Estación Meteorológica de Bajo Costo "Embaco"

**Comment by AO94** [comment]
![img_20180310_123617](https://user-images.githubusercontent.com/37197758/37496913-40fa33c4-2883-11e8-88fb-a327bfaa0c3d.jpg)

**Comment by AO94** [comment]
![auto_save](https://user-images.githubusercontent.com/37197758/37496938-643e1d00-2883-11e8-905e-4a2352bd4f9a.png)

**Comment by AO94** [comment]
![1520565381597](https://user-images.githubusercontent.com/37197758/37496962-84d38802-2883-11e8-95cb-cae4da9981d9.png)

**Comment by AO94** [comment]
![lfinal](https://user-images.githubusercontent.com/37197758/37559724-b8d4674a-29f8-11e8-85b6-22c2d2f53412.jpg)

**Comment by AO94** [comment]
Logo Final.

**Comment by AO94** [comment]
![000](https://user-images.githubusercontent.com/37197758/38003106-9bed5b40-31fb-11e8-8484-0645658626a6.png)
![001](https://user-images.githubusercontent.com/37197758/38003107-9c1341ca-31fb-11e8-88e8-2ff64ef6c20b.png)

**Comment by AO94** [comment]
Buenas noches,

Acabe de subir dos archivos en formato PNG, los cuales representan la infografia del Proyecto, espero la opinión de todos para mejorar el diseño.

Gracias.

**Comment by jmencisom** [comment]
![](https://user-images.githubusercontent.com/37197758/38003107-9c1341ca-31fb-11e8-88e8-2ff64ef6c20b.png)

Me gusta más esta opción. Por favor poner los logos horizontalmente al final de la página debajo del siguiente texto:

Instituciones participantes:

[Logo Unipanamericana] [Logo Unillanos]


Gracias.

**Comment by AO94** [comment]
ok entendido.
