### ISSUE TITLE
Proponer 3 conferencias internacionales 

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/embaco#11]
Por favor proponer 3 conferencias internacionales para presentar el resultado del proyecto.

Gracias.

**Comment by jmencisom** [comment]
**Fecha de entrega 14 de marzo**

**Comment by Julianm07** [comment]
Buenas noches,

Las siguientes son las conferencias próximas a las cuales nos podemos presentar como semillero de investigación:

INGENIO 2018 - Conferencia Internacional de Ingeniería: Agosto 22 a 24 de 2018 Medellín, Antioquia – Colombia.
http://www.udes.edu.co/investigacion/convocatorias/item/1920-ingenio-2018-conferencia-internacional-de-ingenieria.html

Jesuita Networking - Convocatoria de Proyectos de Investigación
https://jesuitnetworking.org/es/call-for-research-projects/


1er Encuentro Nacional de Gestión de Proyectos en Perú Este 22 de septiembre, de 9 a.m. a 7 p.m
http://departamento.pucp.edu.pe/ingenieria/2017/09/14/gestion-de-proyectos-2/

**Comment by jmencisom** [comment]
Perfecto Gracias.
