### ISSUE TITLE
Incribir proyecto evento Cali

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/embaco#14]
![poster](https://user-images.githubusercontent.com/1332546/37257086-378f79e2-2532-11e8-87b6-494cc6e18c79.jpg)
[FORMATO PRELIMINAR REGISTRO PARES Y PONENTES VI ENCUENTRO SEMILLEROS TYT.xlsx](https://github.com/jmencisom/embaco/files/1800737/FORMATO.PRELIMINAR.REGISTRO.PARES.Y.PONENTES.VI.ENCUENTRO.SEMILLEROS.TYT.xlsx)
[Brochure 6to encuentro regional semilleros.pdf](https://github.com/jmencisom/embaco/files/1800738/Brochure.6to.encuentro.regional.semilleros.pdf)

Por favor solicitar apoyo de los compañeros para completar los formatos

Gracias.

**Comment by jmencisom** [comment]
John, por favor completar las pestañas de delegado institucional y ponentes en el archivo FORMATO PRELIMINAR REGISTRO PARES Y PONENTES VI ENCUENTRO SEMILLEROS TYT.xlsx. Tenemos plazo hasta el viernes. Gracias.

**Comment by Jelvismurillo** [comment]
[FORMATO.PRELIMINAR.REGISTRO.PARES.Y.PONENTES.VI.ENCUENTRO.SEMILLEROS.TYT.xlsx](https://github.com/jmencisom/embaco/files/1835406/FORMATO.PRELIMINAR.REGISTRO.PARES.Y.PONENTES.VI.ENCUENTRO.SEMILLEROS.TYT.xlsx)
