### ISSUE TITLE
Listar componentes electrónicos

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/embaco#15]
Jesús,

¿Podría por favor hacer una lista de los componentes electrónicos requeridos (con referencia y URL).

https://github.com/jmencisom/embaco/wiki/Componentes

Gracias.
--Javier

**Comment by jrcarvajal** [comment]
Hola Javier, seria comprar el modulo GSM SIM900, de los otros sensores poco
conozco..


2018-03-12 7:44 GMT-05:00 Javier Enciso <notifications@github.com>:

**Comment by jmencisom** [comment]
ok, ya lo agregé a la página https://github.com/jmencisom/embaco/wiki/Componentes
