### ISSUE TITLE
Cotizar raspberry y arduino

### ISSUE THREAD

**Issue by pbejarano96** [jmencisom/embaco#3]
Cotizar los precios de los sistema de arduino y raspberry para poder decidir cual seria el apropiado para la estación metodología

**Comment by jmencisom** [comment]
¿Cuál es el estado de esta tarea?

**Comment by jmencisom** [comment]
**Fecha de entrega 14 de marzo**

**Comment by pbejarano96** [comment]
![screenshot_20180308-180228](https://user-images.githubusercontent.com/36974319/37804591-f1acbbcc-2e02-11e8-906e-bf9a7b4a8da9.png)

**Comment by pbejarano96** [comment]
Cotización de la raspberry
