### ISSUE TITLE
Realizar Diapositivas EMBAC

### ISSUE THREAD

**Issue by Julianm07** [jmencisom/embaco#6]
En el proceso de construcción de la estación meteorológica a bajo costo es necesario tener una guía en la cual podamos dar a conocer este proyecto.
Uno de los medios que utilizaremos serán las diapositivas en las cuales se va a determinar a manera global las actividades a realizar durante el periodo de tiempo: Febrero/Junio 2018.

**Comment by jmencisom** [comment]
¿Cuál es el estado de esta tarea?

**Comment by jmencisom** [comment]
**Fecha de entrega 14 de marzo**

**Comment by Julianm07** [comment]
[EMBACO.pptx](https://github.com/jmencisom/embaco/files/1813975/EMBACO.pptx)

**Comment by jmencisom** [comment]
Gracias Julian. Debemos plantear un diagrama de bloques con la solución (boards, sensores, etc.)
